apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    git-commit-hash: 98eea0c447ec4dc7d6f6ad81a928b28427ea446f
  creationTimestamp: null
  name: nginx
spec:
  replicas: 5
  strategy: {}
  template:
    metadata:
      annotations:
        app: nginx
      creationTimestamp: null
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 10m
status: {}
